# tache pour le role webserver
---
    - include_vars: "{{ item }}"
    # Définit deux fichiers selon le type de l'OS, ici par défaut c'est Debian,
      with_first_found:
      - "webservers_{{ ansible_os_family | lower }}_vars.yml"
      - webservers_default_vars.yml
    - name: verification du package 
      package:
        name: "{{ apache_name }}"
        state: present
    - name : Vérification du service
      service :
        name : "{{ apache_name }}"
        state: started
        enabled: true
    - name: Parametrage du firewall sur les Redhat
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
      when: "ansible_os_family == 'RedHat'"
    - name: deploiement du fichier index.html
      template:
        dest: /var/www/html/index.html
        src: index.html.j2
