# Tâches pour le rôle webserver
---
- include_vars: "{{ item }}"
  with_first_found:
    - "webserver_{{ ansible_os_family | lower }}_vars.yml"
    - webserver_default_vars.yml
- name: Vérification du package
  package:
    name: "{{ apache_name }}"
    state: present
- name: Service apache démarré et activé
  service:
    name: "{{ apache_name }}"
    state: started
    enabled: True
- name: Paramétrage de firewalld sur les RH-like
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  when: "ansible_os_family == 'RedHat'"
- name: Déploiement du fichier
  template:
    dest: /var/www/html/index.html
    src: index.html.j2
